steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gceme:${SHORT_SHA}', '.' ]

  - id: 'publish'
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/gceme:${SHORT_SHA}' ]